language: node_js
node_js:
  - "12"
install:
  - yarn install --frozen-lockfile
script:
  - yarn clean && yarn build
after_success:
  - yarn bundlewatch
  - yarn bundlesize
deploy:
  provider: script
  script: yarn deploy
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: true
  on:
    branch: master