language: node_js
node_js:
  - "12"
addons:
chrome: stable
install:
  - yarn install --frozen-lockfile
script:
  - yarn clean && yarn build
after_success:
  - yarn bundlewatch
  - yarn bundlesize
  - yarn lhci autorun
deploy:
  provider: script
  script: yarn deploy
  cleanup: false
  keep_history: true
  on:
    branch: master