language: node_js
node_js:
  - "12"
addons:
  chrome: stable
install:
  - yarn install --frozen-lockfile
script:
  - yarn clean && yarn build
after_success:
  - yarn bundlewatch
  - yarn bundlesize
  - yarn lhci autorun --upload.target=temporary-public-storage
deploy:
  provider: script
  script: yarn build --prefix-paths && yarn deploy
  skip_cleanup: true
  on:
    branch: master